### ISSUE TITLE
Could not read allocator for cold pool! Has the DB been created properly?

### ISSUE THREAD

**Issue by thanhtien522** [SoftwareDefinedBuildings/btrdb#47]
I try to run btrdb in Docker with image `btrdb/db:4.6.0` but got these error:
```
db1_1  | [CRITICAL]cephprovider.go:489 > Could not read allocator for cold pool! Has the DB been created properly?
db1_1  | panic: Could not read allocator for cold pool! Has the DB been created properly?
db1_1  |
db1_1  | goroutine 1 [running]:
db1_1  | github.com/op/go-logging.(*Logger).Panic(0xc420149260, 0xc420011920, 0x1, 0x1)
db1_1  | 	/home/immesys/w/go/src/github.com/op/go-logging/logger.go:188 +0xc7
db1_1  | github.com/SoftwareDefinedBuildings/btrdb/internal/cephprovider.(*CephStorageProvider).Initialize(0xc420083a20, 0xf610e0, 0xc420196270)
db1_1  | 	/home/immesys/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/internal/cephprovider/cephprovider.go:489 +0x8f4
db1_1  | github.com/SoftwareDefinedBuildings/btrdb/internal/bstore.NewBlockStore(0xf610e0, 0xc420196270, 0x80, 0xd, 0x0)
db1_1  | 	/home/immesys/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/internal/bstore/blockstore.go:133 +0x303
db1_1  | github.com/SoftwareDefinedBuildings/btrdb.NewQuasar(0xf610e0, 0xc420196270, 0x1, 0xd, 0x0)
db1_1  | 	/home/immesys/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/quasar.go:116 +0x4d
db1_1  | main.main()
db1_1  | 	/home/immesys/w/go/src/github.com/SoftwareDefinedBuildings/btrdb/btrdbd/main.go:113 +0x312
```

My Ceph pool list:
```
ceph osd dump | grep pool
pool 0 'rbd' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 64 pgp_num 64 last_change 2 flags hashpspool stripe_width 0
pool 1 'cephfs_data' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 10 flags hashpspool crash_replay_interval 45 stripe_width 0
pool 2 'cephfs_metadata' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 9 flags hashpspool stripe_width 0
pool 3 '.rgw.root' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 11 owner 18446744073709551615 flags hashpspool stripe_width 0
pool 4 'default.rgw.control' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 13 owner 18446744073709551615 flags hashpspool stripe_width 0
pool 5 'default.rgw.data.root' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 15 owner 18446744073709551615 flags hashpspool stripe_width 0
pool 6 'default.rgw.gc' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 16 owner 18446744073709551615 flags hashpspool stripe_width 0
pool 7 'default.rgw.lc' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 17 owner 18446744073709551615 flags hashpspool stripe_width 0
pool 8 'default.rgw.log' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 8 pgp_num 8 last_change 18 owner 18446744073709551615 flags hashpspool stripe_width 0
pool 11 'btrdb' replicated size 1 min_size 1 crush_ruleset 0 object_hash rjenkins pg_num 128 pgp_num 128 last_change 27 flags hashpspool stripe_width 0
```
I use `btrdb` pool.

And the status of Ceph cluster:
```
ceph -s
    cluster 136dff26-fe9d-4513-b5f3-7ba1b290a609
     health HEALTH_OK
     monmap e2: 1 mons at {ccb1.circeboard.com=10.174.7.90:6789/0}
            election epoch 7, quorum 0 ccb1.circeboard.com
      fsmap e5: 1/1/1 up {0=mds-ccb1.circeboard.com=up:active}
        mgr no daemons active
     osdmap e28: 1 osds: 1 up, 1 in
            flags sortbitwise,require_jewel_osds,require_kraken_osds
      pgmap v148: 256 pgs, 10 pools, 3829 bytes data, 224 objects
            40092 kB used, 102209 MB / 102249 MB avail
                 256 active+clean
```

Any one know what should i do?

**Comment by pingthings** [comment]
Did you start the 4.6 image on a previously installed version of BTrDB?  From 4.6 forward there is a requirement for an additional storageclass that needs to be assigned.  I am not sure that this is the exact problem but could be potentially the issue.  @immesys would have the ultimate answer.  

You might try creating the additional storageclass in Kubernetes,  etcd-backup-gce-pd

**Comment by immesys** [comment]
You need to run the init script to initialize the database. In the smartgridstore installer there is a kubernetes job to do that.

**Comment by thanhtien522** [comment]
I deployed manually with Docker compose so might be i missed this step. I will try again.

Thank you for your reply.
